[package]
name = "untitled"
version = "0.1.0"
authors = ["chao.yang <chao.yang.phoenixstudio@puzzleplusgames.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3"
num-traits = "0.2"
winit = "0.18"

